# Generated by Django 4.2.4 on 2023-08-24 16:03

import django.contrib.gis.db.models.fields
from django.db import migrations

from django.contrib.postgres.operations import CreateExtension

operations = [
        CreateExtension('postgis_raster'),
]
class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_alter_elevation_rast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevation',
            name='rast',
            field=django.contrib.gis.db.models.fields.RasterField(srid=4326),
        ),
    ]
